### ISSUE TITLE
[Window] 'Maximise' button on undecorated Aurora window fullscreens rather than maximises

### ISSUE THREAD

**Issue by russellbanks** [kirill-grouchnikov/aurora#13]
When using an undecorated Aurora Window, the maximising button (square) makes the window fullscreen rather than maximising it. For reference, I am using Windows 11 so normally pressing a maximise button would make the window fill the screen whilst staying above the taskbar and keeping the taskbar visible.

**Comment by kirill-grouchnikov** [comment]
The relevant code is in the block that [starts here](https://github.com/kirill-grouchnikov/aurora/blob/icicle/window/src/desktopMain/kotlin/org/pushingpixels/aurora/window/AuroraWindow.kt#L195) which is asking the underlying `JFrame` to set its extended state to `MAXIMIZED_BOTH`.

Apparently it's a [20 (!!!) year old bug](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=4737788) in Java, and the workaround is to explicitly compute and set maximized bounds on each undecorated frame.

**Comment by kirill-grouchnikov** [comment]
There's more to it. There were multiple fixes that went into Java 15 that changed what needs to be passed to `setMaximizedBounds`. See:

* https://bugs.openjdk.java.net/browse/JDK-8176359
* https://bugs.openjdk.java.net/browse/JDK-8231564
* https://bugs.openjdk.java.net/browse/JDK-8243925

On pre-Java 15, the result of `GraphicsConfiguration.getBounds()` needs to be scaled by the display's scale factor (obtained from `GraphicsConfiguration.getDefaultTransform().getScaleX/Y()` before applying the screen insets.

**Comment by russellbanks** [comment]
Just wondering, how come it can't be done like the [Compose Window tutorial](https://github.com/JetBrains/compose-jb/tree/master/tutorials/Window_API_new#changing-the-state-maximized-minimized-fullscreen-size-position-of-the-window)? Is there a limitation or a reason why using `JFrame` is preferable?

![Changing the state](https://raw.githubusercontent.com/JetBrains/compose-jb/master/tutorials/Window_API_new/state.gif)

**Comment by kirill-grouchnikov** [comment]
The example you're linking to is not an undecorated window. You can see the OS-provided decorations (the title bar, the window border, etc). Now if you change it to undecorated mode, you'll get the same issue:

```
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.material.Checkbox
import androidx.compose.material.Text
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.Window
import androidx.compose.ui.window.WindowPlacement
import androidx.compose.ui.window.WindowPosition
import androidx.compose.ui.window.application
import androidx.compose.ui.window.rememberWindowState

fun main() = application {
    val state = rememberWindowState(placement = WindowPlacement.Floating)

    Window(onCloseRequest = ::exitApplication, state, undecorated = true) {
        Column(modifier = Modifier.padding(16.dp).fillMaxSize()) {
            Row(verticalAlignment = Alignment.CenterVertically) {
                Checkbox(
                    state.placement == WindowPlacement.Fullscreen,
                    {
                        state.placement = if (it) {
                            WindowPlacement.Fullscreen
                        } else {
                            WindowPlacement.Floating
                        }
                    }
                )
                Text("isFullscreen")
            }

            Row(verticalAlignment = Alignment.CenterVertically) {
                Checkbox(
                    state.placement == WindowPlacement.Maximized,
                    {
                        state.placement = if (it) {
                            WindowPlacement.Maximized
                        } else {
                            WindowPlacement.Floating
                        }
                    }
                )
                Text("isMaximized")
            }

            Row(verticalAlignment = Alignment.CenterVertically) {
                Checkbox(state.isMinimized, { state.isMinimized = !state.isMinimized })
                Text("isMinimized")
            }

            Text(
                "Position ${state.position}",
                Modifier.clickable {
                    val position = state.position
                    if (position is WindowPosition.Absolute) {
                        state.position = position.copy(x = state.position.x + 10.dp)
                    }
                }
            )

            Text(
                "Size ${state.size}",
                Modifier.clickable {
                    state.size = state.size.copy(width = state.size.width + 10.dp)
                }
            )

            Box(modifier = Modifier.fillMaxSize().weight(1.0f, true).background(Color.Red))
        }
    }
}
```

**Comment by kirill-grouchnikov** [comment]
As for your other questions:

- `ComposeWindow` is just [a fancy](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/ui/ui/src/desktopMain/kotlin/androidx/compose/ui/awt/ComposeWindow.desktop.kt;l=38) Swing `JFrame`
- `WindowPlacement.Maximized` is just [a fancy wrapper](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/ui/ui/src/desktopMain/kotlin/androidx/compose/ui/awt/ComposeWindow.desktop.kt;l=146) around [the underlying](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/ui/ui/src/desktopMain/kotlin/androidx/compose/ui/awt/ComposeWindow.desktop.kt;l=172) `extendedState` of the `JFrame`

**Comment by russellbanks** [comment]
Perfect explanation, thank you!
