### ISSUE TITLE
[Window] Add ability to set rounded corners on an undecorated Aurora window

### ISSUE THREAD

**Issue by russellbanks** [kirill-grouchnikov/aurora#15]
In Windows 11, rounded corners for windows were introduced. Of course, with an undecorated window and the nature of Java being cross-platform, it does not inherit this functionality from the operating system.

Therefore, it would be good if, for example, there was the ability to make the corners rounded, or have the corners automatically round when on Windows 11. I imagine this could be done by allowing the window to have a certain shape (of which `RoundedRectangle()` could be passed) or through a parameter of `roundedCorners = true`. Hopefully, this would then make Aurora applications feel more native for Windows 11 whilst maintaining cross-platform functionality.

![Window with rounded corners](https://www.windowslatest.com/wp-content/uploads/2021/06/Control-Panel-update.jpg)

**Comment by kirill-grouchnikov** [comment]
I do not have plans to support rounded corners, any sort of translucency, drop shadows or acrylic / aero / anything similar on top-level windows.

**Comment by jackdevey** [comment]
How come - is there any reason why?

**Comment by kirill-grouchnikov** [comment]
Window translucency (Aero / Acrylic on Windows, and general translucent areas on macOS) require usage of native APIs. Beyond the additional complexity required to build and test such dependencies across different OSes, there is the inescapable cost that comes with trying to keep up with the ever evolving native capabilities. See [my post](https://www.pushing-pixels.org/2022/01/19/native-fidelity.html) on this from yesterday.

These are also design trends that last for a few years, to be replaced with something different. I build Radiance and Aurora for a longer time span, and do not chase such trends. 

If an interested third-party wants to provide native integration for windows-level features (such as, let's say, [snap layouts](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/apply-snap-layout-menu) on Windows 11), I will consider providing support in Aurora for configuring Aurora-provided title pane with such integration points. But I will not be in the business of chasing short term fads from OS vendors.

**Comment by russellbanks** [comment]
> If an interested third-party wants to provide native integration for windows-level features (such as, let's say, [snap layouts](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/apply-snap-layout-menu) on Windows 11), I will consider providing support in Aurora for configuring Aurora-provided title pane with such integration points. But I will not be in the business of chasing short term fads from OS vendors.

Following this, could there potentially be a future integration of Aurora with [Compose Window Styler](https://github.com/MayakaApps/ComposeWindowStyler)?

![Compose Window Styler](https://raw.githubusercontent.com/MayakaApps/ComposeWindowStyler/main/res/demo_preview.webp)

**Comment by kirill-grouchnikov** [comment]
Is there anything that stops you from using both of these projects together today?

**Comment by russellbanks** [comment]
> Is there anything that stops you from using both of these projects together today?

ComposeWindowStyler requires [FrameWindowScope](https://github.com/MayakaApps/ComposeWindowStyler/blob/2c4e52472516fe34c5b5fb24d3ce6c11f1a45535/window-styler/src/jvmMain/kotlin/com/mayakapps/compose/windowstyler/WindowStyle.kt) whereas an AuroraWindow provides AuroraWindowScope/WindowScope.

Edit: I have been able to get this working by creating an extension function:

```kt
@Composable
private fun WindowScope.WindowStyle(isDarkTheme: Boolean, backdropType: WindowBackdrop = WindowBackdrop.Mica) {
    val manager = remember { WindowManager(window as JFrame, isDarkTheme, backdropType) }

    LaunchedEffect(isDarkTheme) {
        manager.isDarkTheme = isDarkTheme
    }

    LaunchedEffect(backdropType) {
        manager.backdropType = backdropType
    }
}
```

**Comment by kirill-grouchnikov** [comment]
Looks like that could be WindowScope instead, unless they have plans to only limit it to frames and not dialogs

**Comment by russellbanks** [comment]
> Looks like that could be WindowScope instead, unless they have plans to only limit it to frames and not dialogs

I made an issue about this exact thing, and they've changed it to use WindowScope, so it will work with Aurora without any extra code needed.

**Comment by kirill-grouchnikov** [comment]
Thanks. If you experiment with integrating these two projects together, please let me know if you run into anything that is blocking you on the Aurora side of things.
