### ISSUE TITLE
Decorated windows miscalculate popup locations

### ISSUE THREAD

**Issue by sproctor** [kirill-grouchnikov/aurora#2]
I'm testing on Linux. Things work as expected in the demo, but if you set `undecorated` to `false`, the popups are about the height of the window title bar too high.

**Comment by kirill-grouchnikov** [comment]
Thanks, will fix. Probably worth spinning 1.0.1 for and not to wait until 1.1

**Comment by kirill-grouchnikov** [comment]
Will spin a 1.0.1 release later today

**Comment by kirill-grouchnikov** [comment]
1.0.1 is live on Maven Central
