### ISSUE TITLE
[Window] Add APIs for configuring the window title pane

### ISSUE THREAD

**Issue by TheDome0** [kirill-grouchnikov/aurora#23]
`undecorated = true` disables os decoration but adds an Aurora specific frame and title bar to the window.

Aside from pure design aspects regarding the border or button icons (minimize, maximize, close), sometimes not all buttons are desired or even new, custom components are needed. The menu bar isn't always sufficient for this.

Opera GX might be a good example of what could be possible
![image](https://user-images.githubusercontent.com/85122272/162788354-ccaae30b-780d-4ef2-a224-65c74b1d33b0.png)

**Comment by kirill-grouchnikov** [comment]
So I want to take a bit of time to make the right APIs for this area. From my current experience with [Radiance](https://github.com/kirill-grouchnikov/radiance), there are 2/3 layers to this:

1. Marking a window to be decorated or undecorated. 
2a. Marking the content of a window to extend into a custom decorated title pane area.
2b. Providing APIs to contribute decorated title pane area content that is styled consistently.

Addressing the first one would require a breaking change in `AuroraWindow`, replacing the `Boolean` decorated flag with a enum: `System` (default, title pane is provided by the operating system), `Themed` (name to be finalized, title pane is provided by Aurora), `None` (no title pane).

The second part is to enable the so-called "unified" title pane appearance (different UI toolkits call it a different name):

<img width="946" alt="visor1" src="https://user-images.githubusercontent.com/52874/162806179-ee665a04-3449-4d6e-82cb-5d9b88c96686.png">

<img width="946" alt="visor2" src="https://user-images.githubusercontent.com/52874/162806173-5ca4445d-3446-40bd-9a16-863a86837892.png">

The last part is to allow app code to add one or more title pane control buttons (in addition to minimize, maximize and close) and have those be styled consistently by Aurora.

Ideally, all of these would be done in a single pass for a more coherent and cohesive API surface, so it might take a bit.

**Comment by kirill-grouchnikov** [comment]
I'm going to move this (and an additional Window-level API to allow the app to "participate" in the user decision to close the window) to version 1.3.

**Comment by kirill-grouchnikov** [comment]
<img width="846" alt="chat-frame" src="https://user-images.githubusercontent.com/52874/201811220-33a956e0-697d-40fe-9284-e85fe20c75bd.png">

**Comment by kirill-grouchnikov** [comment]
This is now available in 1.3-SNAPSHOT.

https://github.com/kirill-grouchnikov/aurora/blob/icicle/demo/src/desktopMain/kotlin/org/pushingpixels/aurora/demo/AuroraTitlePaneDemo.kt has some sample code for configuring the positioning of app icon, title and control buttons for windows decorated by Aurora.

https://github.com/kirill-grouchnikov/aurora/blob/icicle/demo/src/desktopMain/kotlin/org/pushingpixels/aurora/demo/titlepane/ChatFrame.kt is a simple example of an integrated title pane where the app content extends into the window title pane (screenshot from a couple comments above).

I will add another demo in the next few days, and add documentation on using these APIs.

**Comment by kirill-grouchnikov** [comment]
<img width="966" alt="mail-frame" src="https://user-images.githubusercontent.com/52874/202238498-914c980f-a633-4f93-a26f-4c86bee0b444.png">

From [this demo](https://github.com/kirill-grouchnikov/aurora/tree/icicle/demo/src/desktopMain/kotlin/org/pushingpixels/aurora/demo/titlepane/mail)

**Comment by kirill-grouchnikov** [comment]
Documentation at https://github.com/kirill-grouchnikov/aurora/blob/icicle/docs/window/TitlePane.md
