### ISSUE TITLE
[Component] Command Menus should toggle when opening and closing

### ISSUE THREAD

**Issue by russellbanks** [kirill-grouchnikov/aurora#26]
### Bug Description

Command Menus should toggle to open, rather than opening every time that they are clicked (resulting in it having to close and re-open).

Actual Result:

The command menu opens and closes every time it is clicked. One click opens it and a second click closes and opens it again.

![java_tsYkSPqpBl](https://user-images.githubusercontent.com/74878137/164348286-fa434c4c-bbe1-4721-b5e1-ddd4fc0cc33b.gif)

Expected Result:

The command group menu should toggle. One click should open it and a second click should close it (as well as being able to click elsewhere).

![idea64_4gnyMfxLhm](https://user-images.githubusercontent.com/74878137/164348461-3e314c74-b47f-4b7f-80ef-b666b96b4e6e.gif)

### Platform Info

Aurora Version: 1.1.0

Operating System: Windows 11

**Comment by kirill-grouchnikov** [comment]
Should also do the same for Radiance command buttons
