### ISSUE TITLE
[Component] Add dividers in command menus

### ISSUE THREAD

**Issue by russellbanks** [kirill-grouchnikov/aurora#27]
### Description

Many types of applications often divide their menu items up to emphasise and group certain options. It would be useful if there were a way to do this in Aurora.

#### Current Result:

All items in command menus are grouped together.

![java_ZQ7uTAH77W](https://user-images.githubusercontent.com/74878137/164895767-02eefe5b-c794-4ebd-b105-ad7a253f5532.gif)

#### Aim:

Dividers could be used to split up groups of options, like the `HorizontalSeparatorProjection`, but in a command menu.

![GitHubDesktop_Mf7TMeoPpN](https://user-images.githubusercontent.com/74878137/164895778-0ca9d42f-df63-4b55-bf5c-cf615842be33.gif)

### Platform Info

Aurora Version: 1.1.0

**Comment by kirill-grouchnikov** [comment]
This should be available already if you use multiple command groups. The horizontal separators should be shown between groups of commands in the menu.

**Comment by russellbanks** [comment]
Just what I was looking for, thank you.
