### ISSUE TITLE
[Component] Table 

### ISSUE THREAD

**Issue by KluDev** [kirill-grouchnikov/aurora#28]
It would be nice to have a table component.

**Comment by kirill-grouchnikov** [comment]
Same as Aurora does not provide its own list or grid, I do not have absolutely any plans to provide a table component. We're talking about grouping, filtering, single and multi-column filtering, pivots, multirow headers, footers, search, freezing rows and columns, pinning rows during scrolling, column / row / cell selection, nesting, cell spans - just as the very basic features that "would be nice". Even a small part of this is well outside the scope of what I can do within Aurora.
