### ISSUE TITLE
[Component] Pressing delete at the end of an AuroraTextField causes a crash.

### ISSUE THREAD

**Issue by russellbanks** [kirill-grouchnikov/aurora#31]
Pressing delete at the end of an AuroraTextField (TextFieldStringProjection shown below) causes a `java.lang.IllegalArgumentException: end cannot negative. [end: -1]` error.

![java_jNlk31JH3y](https://user-images.githubusercontent.com/74878137/166903662-9436a0f6-2bc6-41d5-b6d2-21f652f47da7.gif)

**Comment by russellbanks** [comment]
Likely linked to [#2023](https://github.com/JetBrains/compose-jb/issues/2023) on Compose-JB.

**Comment by kirill-grouchnikov** [comment]
Not seeing the crash in the latest dev version 1.2-SNAPSHOT. But yes, in this particular case Aurora [wraps the core](https://github.com/kirill-grouchnikov/aurora/blob/icicle/component/src/desktopMain/kotlin/org/pushingpixels/aurora/component/AuroraTextField.kt#L413) `BasicTextField` and all the text handling including backspace / delete comes from that layer.
