### ISSUE TITLE
SVG Transcoder Gradle Plugin uses incorrect property annotation

### ISSUE THREAD

**Issue by msfjarvis** [kirill-grouchnikov/aurora#33]
In `TranscodeTask` the `outputDirectory` property [here](https://github.com/kirill-grouchnikov/aurora/blob/434b33eb252cd205792ff4c07827d7f79f2ec84d/tools/svg-transcoder-gradle-plugin/src/main/kotlin/org/pushingpixels/aurora/tools/svgtranscoder/gradle/TranscodeTask.kt#L46) is annotated with [`@get:InputDirectory`](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/InputDirectory.html), which should probably be [`@get:OutputDirectory`](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/OutputDirectory.html) instead. I have [a commit](https://msfjarvis.dev/g/aurora/37a79428458e
) on my fork that can be cherry-picked or I can send a proper PR if required.

**Comment by kirill-grouchnikov** [comment]
Thanks, this has been fixed now
