### ISSUE TITLE
SVG transcoder not multiplatform capable

### ISSUE THREAD

**Issue by mipastgt** [kirill-grouchnikov/aurora#39]
I transcoded some icons with the SVG transcoder Gradle plugin but found that the generated Painters are not multiplatform capable. They contain the following import statements:

```
import androidx.compose.ui.geometry.*
import androidx.compose.ui.graphics.*
import androidx.compose.ui.graphics.drawscope.DrawScope
import androidx.compose.ui.graphics.drawscope.Fill
import androidx.compose.ui.graphics.drawscope.Stroke
import androidx.compose.ui.graphics.drawscope.clipRect
import androidx.compose.ui.graphics.drawscope.translate
import androidx.compose.ui.graphics.drawscope.withTransform
import androidx.compose.ui.graphics.painter.Painter
import java.lang.ref.WeakReference
import java.util.*
import kotlin.math.min
```
where these two
```
import java.lang.ref.WeakReference
import java.util.*

```
are the culprit. The Java dependencies are clearly not multiplatform but luckily they do not even seem to be needed. If I just delete them everything is fine. It would be nice though if you could change the transcoder, so that they are not generated at all and the output could then be used directly without having to manually fiddle with the code.

Cheers
Michael

**Comment by kirill-grouchnikov** [comment]
No part of Aurora is intended to be multiplatform capable. The only supported platform is desktop.

As for the specific references - they are used for transcoded `<image>` nodes. See [documentation](https://github.com/kirill-grouchnikov/aurora/blob/icicle/docs/tools/svg-transcoder/internals.md#addendum-c---handling-rasterimagenode) and a sample [transcoded file](https://github.com/kirill-grouchnikov/aurora/blob/icicle/demo/src/desktopMain/kotlin/org/pushingpixels/aurora/demo/svg/random/kirill.kt)

**Comment by mipastgt** [comment]
That's a pity. Could the generation of the import statements be made conditional depending on whether they are needed or not?

**Comment by kirill-grouchnikov** [comment]
That would open the door to committing to something that I very much intentionally have no plans to commit to. Aurora is targeting only the desktop environment.
