### ISSUE TITLE
[Theming] Add Catppuccin as a theme

### ISSUE THREAD

**Issue by russellbanks** [kirill-grouchnikov/aurora#42]
[Catppuccin](https://github.com/catppuccin/catppuccin) is a well-defined pastel theme, and I feel it could be a nice addition to the Aurora framework, just as a theme option. I appreciate that this deviates from the traditional Java feel of these desktop apps, but it can illustrate a more modern aesthetic for the user interface.

![image](https://user-images.githubusercontent.com/74878137/195850275-ec885312-3e59-4881-ad3a-ac1e04a66086.png)

There are many apps that integrate Catppuccin as a theme due to its popularity, such as [FreeTube](https://github.com/FreeTubeApp/FreeTube/pull/2395).

If this isn't suitable to add to Aurora however, it would be a big help if you could give some guidance on creating this myself, thanks!

**Comment by kirill-grouchnikov** [comment]
See documentation under the [theming section](https://github.com/kirill-grouchnikov/aurora#theming) - it talks about the basic building blocks (color schemes, color scheme association kinds, color scheme bundles, painters) and how to define a whole skin. 

And you can look at the source code of individual Aurora skins to see how various parts come together.
