### ISSUE TITLE
[Window] Window decoration buttons look blurry is blocky on non high-res displays

### ISSUE THREAD

**Issue by sschuberth** [kirill-grouchnikov/aurora#55]
I'm all new to Aurora and Compose in general, so I'm sorry if this is a know issue or has been discussed before. But when giving the `HelloWorld.kt` application a try, the created window has quite blurry icons in its title bar. Most notably the "maximize" button looks really bad:

![image](https://user-images.githubusercontent.com/349154/205747058-db22f220-aba7-417d-aa56-6fa26517d4cf.png)

That's very different from the crisp screenshots over [here](https://github.com/kirill-grouchnikov/ephemeral/blob/breeze/docs/theming/skins/toneddown.md#mariner).

Also the application preview windows rendered by Windows when hovering over the app's entry in the taskbar looks very blocky:

![image](https://user-images.githubusercontent.com/349154/205744940-e27b5e2c-15a4-4588-a0d7-1162abaebc09.png)

Is this something I can fix on my side by tweaking some application settings?

PS: My display scale is at 100%, so I don't expect Windows to interfere here.

**Comment by kirill-grouchnikov** [comment]
What is your monitor resolution? The documentation screenshots are taken on a retina / high-res display.

How does that window look like if you replace `windowTitlePaneConfiguration` with `AuroraWindowTitlePaneConfigurations.System`?

Also, can you attach a screenshot of running the `AuroraDemo` demo? I'd like to see how other components look like, such as checkboxes, comboboxes, etc.

**Comment by kirill-grouchnikov** [comment]
<img width="437" alt="image" src="https://user-images.githubusercontent.com/52874/205751154-f64012dd-5043-4dee-951d-c51036fe9eb5.png">

Looks like in this particular case, some of the icons can be made better by snapping the lines, maybe

**Comment by sschuberth** [comment]
> What is your monitor resolution?

It's 2560 x 1440 pixels.

**Comment by sschuberth** [comment]
> How does that window look like if you replace `windowTitlePaneConfiguration` with `AuroraWindowTitlePaneConfigurations.System`?

Better, the buttons are now crisp, and the preview is not blocky anymore, but a bit blurry:

![image](https://user-images.githubusercontent.com/349154/205754939-45c2548a-8dad-4a29-a371-27ffd51b8f87.png)

**Comment by kirill-grouchnikov** [comment]
Those buttons are rendered by Windows, so it's expected they look better.

I'll take a look at tweaking the logic of the Aurora-provided window title pane icons in a few days once 1.4-SNAPSHOT version starts.

As for the preview, I don't think I can control any of that logic of how Windows decides to scale application window content into its preview thumbnails.

**Comment by sschuberth** [comment]
> Also, can you attach a screenshot of running the `AuroraDemo` demo? I'd like to see how other components look like, such as checkboxes, comboboxes, etc.

Here you go:

![image](https://user-images.githubusercontent.com/349154/205757101-4ba4bc72-d69a-402f-9899-4f010dcaf74e.png)

**Comment by sschuberth** [comment]
> As for the preview, I don't think I can control any of that logic of how Windows decides to scale application window content into its preview thumbnails.

Looks like you actually *can* render the preview yourself: https://learn.microsoft.com/en-us/windows/win32/dwm/dwm-sample-customizethumbnail

However, I have no idea why the preview looks so much better with `AuroraWindowTitlePaneConfigurations.System` than with `AuroraWindowTitlePaneConfigurations.AuroraPlain()`.

**Comment by kirill-grouchnikov** [comment]
I'm not going to use any native, platform specific APIs in Aurora, so the live preview part is going to be out of scope.
